### ISSUE TITLE
flake-compat not present in flake.lock

### ISSUE THREAD

**Issue by bsima** [aldoborrero/mynixpkgs#6]
The description in the readme about how to use with niv does not work because flake-compat is not in your lock file:

                                                                                                                               
       error: attribute 'flake-compat' missing                           
                               
       at /nix/store/7fijhv3dkfcad40adlfb0ibk0n4d3xnr-mynixpkgs-src/flake-compat.nix:7:12:                                                         
                               
            6|   lock = builtins.fromJSON (builtins.readFile flakeLockPath);                                                                       
            7|   inherit (lock.nodes.flake-compat.locked) owner repo rev narHash;                                                                  
             |            ^  
            8|

**Comment by aldoborrero** [comment]
Thanks for letting me know @bsima (I added it long time ago, so it should be solved now)
